version: '3.8'

services:
  api:
    build:
      context: .
    container_name: monitoring_api
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: monitoring_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: monitoring
      MYSQL_USER: root
    volumes:
      - mysql_data:/var/lib/mysql        
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
