services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=passwordroot
      - DB_NAME=MonitoringAPI_db
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: passwordroot
      MYSQL_DATABASE: MonitoringAPI_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: