# Base image
FROM node:latest

# Set working directory
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source files
COPY ./src ./src
COPY ./public ./public

# Expose the port
EXPOSE 8080

# Start the application
CMD ["node", "src/app.js"]